export type SoccerTeam = {
  id: string;
  name: string;
  full_name?: string | null;
  short_name?: string | null;
  abbreviation: string | null;
  logo: string | null;
  league: string | null;
  conference: string | null;
  division: string | null;
  wins: number;
  draws: number;
  losses: number;
  points: number | null;
  goals_for: number | null;
  goals_against: number | null;
  goal_difference: number | null;
  wins_home: number | null;
  losses_home: number | null;
  wins_away: number | null;
  losses_away: number | null;
  standing_rank: number | null;
  streak: string | null;
};

export type SoccerPlayer = {
  id: string;
  first_name: string;
  last_name: string;
  display_name: string;
  country: string | null;
  photo: string | null;
  position: string | null;
  jersey_number: string | null;
  height: string | null;
  weight: string | null;
  birth_date: string | null;
  league: string | null;
  team_id: string | null;
  enet_id: string | null;
};

export type SoccerGame = {
  id: string;
  league: string | null;
  status: "scheduled" | "live" | "finished";
  status_detail: string | null;
  period: number | null;
  period_time: string | null;
  penalty_shootout: boolean | null;
  extra_time: boolean | null;
  scheduled_at: string | null;
  home_score: number | null;
  away_score: number | null;
  home_score_h1: number | null;
  home_score_h2: number | null;
  away_score_h1: number | null;
  away_score_h2: number | null;
  home_score_et: number | null;
  away_score_et: number | null;
  home_score_pen: number | null;
  away_score_pen: number | null;
  home_team: SoccerTeam | null;
  away_team: SoccerTeam | null;
  enet_event_id: string | null;
  venue_name: string | null;
  venue_city: string | null;
  venue_country: string | null;
  venue_capacity: number | null;
  round: string | null;
  spectators: number | null;
  started_at: string | null;
  ended_at: string | null;
};
